apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-app
  name: nodejs-svc
  namespace: nodejs-pipeline
spec:
  ports:
  - nodePort: 32334
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodejs-app
  type: NodePort